name: create and publish docker images
on:
  workflow_call:
    inputs:
      docker_repo:
        required: true
        type: string
        description: "The docker hub repo for the specific application"
      tag:
        required: false
        type: string
        description: "docker tag on the containers"
      dockerfile_location:
        required: true
        type: string
        description: "The path to the docker file for example './<dir>/<dir>/Dockerfile' "

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
        
      - name: disable safe dir
        uses: srt32/git-actions@v0.0.3
        with:
          args: git config --global --add safe.directory '*'
          
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # Login into DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=${{ github.ref_name}}" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # pushing the images
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile_location }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.docker_repo }}:${{ env.final_tag }}
