name: deployment process
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: server deployment
    steps:
      - name: Install SSH KEY
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_KEY_PAIR }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts
      - name: Deploy OVER SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} ./deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
