name: app pipeline

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker
        uses: Conclase-Technologies/pipelineWorkflow/.github/workflows/build_and_push_docker_images.yml@main
        with:
          docker_repo:
          tag:
          dockerfile_location:
        secrets: inherit
        # secrets:
        #   DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        #   DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: server_connection
        uses: Conclase-Technologies/pipelineWorkflow/.github/workflows/deployment.yml@main
        secrets: inherit
